// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Image11;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;

extern lv_obj_t * ui_Panel1; 
extern lv_obj_t * ui_Panel2; 
extern lv_obj_t * ui_Panel3; 
extern lv_obj_t * ui_Panel4; 
extern lv_obj_t * ui_Panel5; 
extern lv_obj_t * ui_Panel6; 
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Panel8;  

extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_btc_logo1_png);    // assets\btc_logo1.png
LV_IMG_DECLARE(ui_img_wifi_logo3_png);    // assets\wifi_logo3.png
LV_IMG_DECLARE(ui_img_wifi_logo2_png);    // assets\wifi_logo2.png

//LV_FONT_DECLARE(ui_font_Display22);
LV_FONT_DECLARE(ui_font_Display24);
LV_FONT_DECLARE(ui_font_Display48);
LV_FONT_DECLARE(ui_font_MontBig);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
